# Generated by Django 5.2.5 on 2025-08-27 12:03

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=25, prefix='ADS', unique=True)),
                ('account_number', models.CharField(max_length=10)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, max_length=12)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In-Active')], default='active', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('set_amount', models.BooleanField(default=False)),
                ('account_pin', models.IntegerField(blank=True, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('contributing_amount', models.DecimalField(decimal_places=2, default=200.0, max_digits=12, max_length=12)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, max_length=12)),
                ('transaction_status', models.CharField(default='Failed', max_length=20)),
                ('ref_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=20, max_length=25, prefix='TRN-', unique=True)),
                ('counts', models.CharField(default=0, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
