# Generated by Django 5.2.5 on 2025-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Widthdrawal', 'Widthdrawal')], default='Deposit', max_length=50),
        ),
    ]
