# Generated by Django 5.2.5 on 2025-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contributing_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=12),
        ),
    ]
