# Generated by Django 5.2.5 on 2025-08-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_all_user_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='counts',
        ),
    ]
