# Generated by Django 5.2.5 on 2025-08-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_all_user_transaction_user_id_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_user_transaction',
            options={'verbose_name': 'All User Transaction'},
        ),
        migrations.AlterField(
            model_name='account',
            name='contributing_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, max_length=12),
        ),
        migrations.CreateModel(
            name='DividendAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=200)),
                ('dividend', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
            ],
        ),
    ]
