# Generated by Django 5.2.5 on 2025-08-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_account_agent_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Failed', 'Failed')], default='Success', max_length=20),
        ),
    ]
