# Generated by Django 5.2.5 on 2025-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdraw_approved',
            field=models.BooleanField(default=False),
        ),
    ]
