# Generated by Django 5.2.5 on 2025-08-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_transaction_withdraw_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
